name: Flask Application CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set environment variables for Flask app
      - name: Set environment variables
        run: |
          echo "FLASK_APP=app.py" >> $GITHUB_ENV

      # Run tests
      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"  # Ensure it looks for test files with prefix 'test_'
